In [1]:
import numpy as np

In [2]:
#Numpy Assignment Practical Questions only

In [13]:
#Q1.
arr = np.random.randint(1, 101, (3, 3))
print("Original Array:\n", arr)

transposed = arr.T
print("Transposed Array:\n", transposed)

Original Array:
 [[95 16 65]
 [24 38 21]
 [48 55 63]]
Transposed Array:
 [[95 24 48]
 [16 38 55]
 [65 21 63]]


In [15]:
#Q2.
arr = np.arange(10)
print("Original 1D array:\n", arr)

reshaped_2x5 = arr.reshape(2, 5)
print("Reshaped to 2x5:\n", reshaped_2x5)

reshaped_5x2 = arr.reshape(5, 2)
print("Reshaped to 5x2:\n", reshaped_5x2)

Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped to 2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped to 5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [16]:
#Q3.
arr = np.random.rand(4, 4)
print("Original 4x4 array:\n", arr)

padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("6x6 array with border:\n", padded)

Original 4x4 array:
 [[0.01016336 0.82750746 0.69955292 0.37624886]
 [0.87861603 0.3595331  0.89460568 0.4704658 ]
 [0.44270872 0.84667702 0.33169178 0.52586792]
 [0.3439556  0.07015709 0.01327002 0.05155839]]
6x6 array with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.01016336 0.82750746 0.69955292 0.37624886 0.        ]
 [0.         0.87861603 0.3595331  0.89460568 0.4704658  0.        ]
 [0.         0.44270872 0.84667702 0.33169178 0.52586792 0.        ]
 [0.         0.3439556  0.07015709 0.01327002 0.05155839 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [17]:
#Q4.
arr = np.arange(10, 61, 5)
print("Array from 10 to 60 with step 5:\n", arr)

Array from 10 to 60 with step 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [18]:
#Q5.
arr = np.array(['python', 'numpy', 'pandas'])

upper = np.char.upper(arr)
lower = np.char.lower(arr)
title = np.char.title(arr)

print("Uppercase:", upper)
print("Lowercase:", lower)
print("Title case:", title)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


In [19]:
#Q6.
arr = np.array(['python', 'numpy', 'pandas'])

spaced = np.char.join(' ', arr)
print("Spaced words:\n", spaced)

Spaced words:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


In [20]:
#Q7.
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print("Array A:\n", a)
print("Array B:\n", b)

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Array A:
 [[6 8]
 [9 5]]
Array B:
 [[5 4]
 [9 9]]
Addition:
 [[11 12]
 [18 14]]
Subtraction:
 [[ 1  4]
 [ 0 -4]]
Multiplication:
 [[30 32]
 [81 45]]
Division:
 [[1.2        2.        ]
 [1.         0.55555556]]


In [21]:
#Q8.
identity = np.eye(5)
print("5x5 Identity Matrix:\n", identity)

diagonal = np.diag(identity)
print("Diagonal Elements:\n", diagonal)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [22]:
#Q9.
arr = np.random.randint(0, 1000, 100)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

primes = np.array([num for num in arr if is_prime(num)])
print("Prime Numbers:\n", primes)

Prime Numbers:
 [ 61 277 193 811 241 811 239 503  53 227 199 859 269 353 181 227 479 907]


In [23]:
#Q10.
temps = np.random.randint(20, 40, 30)
print("Daily Temperatures:\n", temps)

weekly_avg = np.mean(temps.reshape(6, 5), axis=1)
print("Weekly Averages:\n", weekly_avg)

Daily Temperatures:
 [33 20 37 25 34 25 28 29 31 24 25 20 24 34 26 26 34 29 37 21 22 22 20 32
 38 20 38 26 33 38]
Weekly Averages:
 [29.8 27.4 25.8 29.4 26.8 31. ]
